### ISSUE TITLE
Typegen creates absolute path to nexus-args-validator/dist directory - when using custom output paths it should be relative

### ISSUE THREAD

**Issue by tjsb** [ahmedosama7450/nexus-args-validator#6]
When running graphql codegen, the generated types are included as  an import in our schema types file.

However, the generated path is absolute which breaks things when working as part of a team (we all have different local paths.)

In our codebase, in our makeSchema() call we are using the outputs.typegen directive so that the generated files are generated outside of our node_modules folder.

```
const schema = makeSchema({
...
outputs: {
    schema: `${__dirname}/generated/schema.graphql`,
    typegen: `${__dirname}/generated/schemaTypes.d.ts`
  }
})
...
```

However, when running graphql typegen, it produces an absolute path to the `nexus-args-validator/dist` folder instead of a relative path - which breaks things when sharing code with team members (as we all have different absolute paths on our file systems!)

For example (in `src/generated/schemaTypes.d.ts`):

`
import type { ValidateResolver, TransformResolver } from "/Users/myuser/code/nexus-args-validator/dist"
`

This would work fine if we were not using custom output paths. But it breaks (or at least requires fixing) everytime we commit new code to be shared by the team.

Perhaps there is a way to determine if custom output paths are enabled by Nexus in the plugin API? Or perhaps a flag could be passed into the plugin config to use a node_modules relative path?

Any help appreciated.

**Comment by tjsb** [comment]
Unfortunately on further testing the PR didn't work. Closed for the time being.

**Comment by tjsb** [comment]
For further info on our issue / use-case:

In our codebase, in our makeSchema() call we are using the outputs.typegen directive so that the generated files are generated outside of our node_modules folder.

`
const schema = makeSchema({
...
outputs: {
    schema: `${__dirname}/generated/schema.graphql`,
    typegen: `${__dirname}/generated/schemaTypes.d.ts`
  }
})
...
`

However, when running graphql typegen, it produces an absolute path to the `nexus-args-validator/dist` folder instead of a relative path - which breaks things when sharing code with team members (as we all have different absolute paths on our file systems!)

For example (in `src/generated/schemaTypes.d.ts`):

`
import type { ValidateResolver, TransformResolver } from "/Users/myuser/code/nexus-args-validator/dist"
`

This would work fine if we were not using custom output paths. But it breaks (or is at least requires fixing) everytime we commit new code to be shared by the team.

Perhaps there is a way to determine if custom output paths are enabled by Nexus in the plugin API?

Any help appreciated.

**Comment by ahmedosama7450** [comment]
Assalamualaikum. Hello,
I am not sure if nexus plugin API supports relative paths or not.
I may look into this issue later if you need it, but I recommend you to switch to [pothus](https://github.com/hayes/pothos) because Nexus is no longer maintained AFAIK. Have a look at graphql-nexus/nexus#1139

BTW, [pothus](https://github.com/hayes/pothos) is well maintained, has type-safety without artifacts generation overhead and has so many official plugins including a [validation plugin](https://pothos-graphql.dev/docs/plugins/zod)

**Comment by tjsb** [comment]
@ahmedosama7450 Assalamualaikum!

Many thanks for your response and for bringing the state of the Nexus project to my attention. Obviously, not really great news that Nexus is not being actively maintained - but such is the reality of open source 😄 .

We will consider our options.

Thanks again.
